// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.10.4 (stable) (Tue Dec 9 00:01:55 2025 -0800) on "macos_arm64"
// Module: packages/flutter/src/widgets/date.dart
// Flags: canary, emitLibraryBundle, enableAsserts(true)
dartDevEmbedder.defineLibrary("package:flutter/src/widgets/date.dart", (function load__package$58flutter__src__widgets__date_dart(date) {
  'use strict';
  let core = dartDevEmbedder.importLibrary("dart:core", function(lib) {
    core = lib;
  });
  let dart = dartDevEmbedder.importLibrary("dart:_runtime", function(lib) {
    dart = lib;
  });
  let dartx = dartDevEmbedder.importLibrary("dartx", function(lib) {
    dartx = lib;
  });
  const CT = Object.create({
    _: () => (C, CT)
  });
  (function() {
  }).prototype = date;
  date[dartDevEmbedder.linkSymbol] = function link__date() {
  };
  date[dart.libraryImportUri] = "package:flutter/src/widgets/date.dart";
  return date;
}));
dartDevEmbedder.debugger.setSourceMap("packages/flutter/src/widgets/date.dart", '{"version":3,"sourceRoot":"","sources":[],"names":[],"mappings":"","file":"../../../../../../../../../packages/flutter/src/widgets/date.dart.lib.js"}');

//# sourceMappingURL=date.dart.lib.js.map
