// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.10.4 (stable) (Tue Dec 9 00:01:55 2025 -0800) on "macos_arm64"
// Module: packages/flutter/foundation.dart
// Flags: canary, emitLibraryBundle, enableAsserts(true)
dartDevEmbedder.defineLibrary("package:flutter/foundation.dart", (function load__package$58flutter__foundation_dart(foundation) {
  'use strict';
  let core = dartDevEmbedder.importLibrary("dart:core", function(lib) {
    core = lib;
  });
  let dart = dartDevEmbedder.importLibrary("dart:_runtime", function(lib) {
    dart = lib;
  });
  let dartx = dartDevEmbedder.importLibrary("dartx", function(lib) {
    dartx = lib;
  });
  const CT = Object.create({
    _: () => (C, CT)
  });
  (function() {
  }).prototype = foundation;
  foundation[dartDevEmbedder.linkSymbol] = function link__foundation() {
  };
  foundation[dart.libraryImportUri] = "package:flutter/foundation.dart";
  return foundation;
}));
dartDevEmbedder.debugger.setSourceMap("packages/flutter/foundation.dart", '{"version":3,"sourceRoot":"","sources":[],"names":[],"mappings":"","file":"../../../../../../../packages/flutter/foundation.dart.lib.js"}');

//# sourceMappingURL=foundation.dart.lib.js.map
