// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.10.4 (stable) (Tue Dec 9 00:01:55 2025 -0800) on "macos_arm64"
// Module: packages/flutter/gestures.dart
// Flags: canary, emitLibraryBundle, enableAsserts(true)
dartDevEmbedder.defineLibrary("package:flutter/gestures.dart", (function load__package$58flutter__gestures_dart(gestures) {
  'use strict';
  let core = dartDevEmbedder.importLibrary("dart:core", function(lib) {
    core = lib;
  });
  let dart = dartDevEmbedder.importLibrary("dart:_runtime", function(lib) {
    dart = lib;
  });
  let dartx = dartDevEmbedder.importLibrary("dartx", function(lib) {
    dartx = lib;
  });
  const CT = Object.create({
    _: () => (C, CT)
  });
  (function() {
  }).prototype = gestures;
  gestures[dartDevEmbedder.linkSymbol] = function link__gestures() {
  };
  gestures[dart.libraryImportUri] = "package:flutter/gestures.dart";
  return gestures;
}));
dartDevEmbedder.debugger.setSourceMap("packages/flutter/gestures.dart", '{"version":3,"sourceRoot":"","sources":[],"names":[],"mappings":"","file":"../../../../../../../packages/flutter/gestures.dart.lib.js"}');

//# sourceMappingURL=gestures.dart.lib.js.map
