// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.10.4 (stable) (Tue Dec 9 00:01:55 2025 -0800) on "macos_arm64"
// Module: packages/flutter/material.dart
// Flags: canary, emitLibraryBundle, enableAsserts(true)
dartDevEmbedder.defineLibrary("package:flutter/material.dart", (function load__package$58flutter__material_dart(material) {
  'use strict';
  let core = dartDevEmbedder.importLibrary("dart:core", function(lib) {
    core = lib;
  });
  let dart = dartDevEmbedder.importLibrary("dart:_runtime", function(lib) {
    dart = lib;
  });
  let dartx = dartDevEmbedder.importLibrary("dartx", function(lib) {
    dartx = lib;
  });
  const CT = Object.create({
    _: () => (C, CT)
  });
  (function() {
  }).prototype = material;
  material[dartDevEmbedder.linkSymbol] = function link__material() {
  };
  material[dart.libraryImportUri] = "package:flutter/material.dart";
  return material;
}));
dartDevEmbedder.debugger.setSourceMap("packages/flutter/material.dart", '{"version":3,"sourceRoot":"","sources":[],"names":[],"mappings":"","file":"../../../../../../../packages/flutter/material.dart.lib.js"}');

//# sourceMappingURL=material.dart.lib.js.map
