// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.10.4 (stable) (Tue Dec 9 00:01:55 2025 -0800) on "macos_arm64"
// Module: packages/flutter/semantics.dart
// Flags: canary, emitLibraryBundle, enableAsserts(true)
dartDevEmbedder.defineLibrary("package:flutter/semantics.dart", (function load__package$58flutter__semantics_dart(semantics) {
  'use strict';
  let core = dartDevEmbedder.importLibrary("dart:core", function(lib) {
    core = lib;
  });
  let dart = dartDevEmbedder.importLibrary("dart:_runtime", function(lib) {
    dart = lib;
  });
  let dartx = dartDevEmbedder.importLibrary("dartx", function(lib) {
    dartx = lib;
  });
  const CT = Object.create({
    _: () => (C, CT)
  });
  (function() {
  }).prototype = semantics;
  semantics[dartDevEmbedder.linkSymbol] = function link__semantics() {
  };
  semantics[dart.libraryImportUri] = "package:flutter/semantics.dart";
  return semantics;
}));
dartDevEmbedder.debugger.setSourceMap("packages/flutter/semantics.dart", '{"version":3,"sourceRoot":"","sources":[],"names":[],"mappings":"","file":"../../../../../../../packages/flutter/semantics.dart.lib.js"}');

//# sourceMappingURL=semantics.dart.lib.js.map
