// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.10.4 (stable) (Tue Dec 9 00:01:55 2025 -0800) on "macos_arm64"
// Module: packages/flutter_mate/src/snapshot/combined_snapshot.dart
// Flags: canary, emitLibraryBundle, enableAsserts(true)
dartDevEmbedder.defineLibrary("package:flutter_mate/src/snapshot/combined_snapshot.dart", (function load__package$58flutter_mate__src__snapshot__combined_snapshot_dart(combined_snapshot) {
  'use strict';
  let core = dartDevEmbedder.importLibrary("dart:core", function(lib) {
    core = lib;
  });
  let dart = dartDevEmbedder.importLibrary("dart:_runtime", function(lib) {
    dart = lib;
  });
  let dartx = dartDevEmbedder.importLibrary("dartx", function(lib) {
    dartx = lib;
  });
  const CT = Object.create({
    _: () => (C, CT)
  });
  (function() {
  }).prototype = combined_snapshot;
  combined_snapshot[dartDevEmbedder.linkSymbol] = function link__combined_snapshot() {
  };
  combined_snapshot[dart.libraryImportUri] = "package:flutter_mate/src/snapshot/combined_snapshot.dart";
  return combined_snapshot;
}));
dartDevEmbedder.debugger.setSourceMap("packages/flutter_mate/src/snapshot/combined_snapshot.dart", '{"version":3,"sourceRoot":"","sources":[],"names":[],"mappings":"","file":"../../../../../../../../../packages/flutter_mate/src/snapshot/combined_snapshot.dart.lib.js"}');

//# sourceMappingURL=combined_snapshot.dart.lib.js.map
