// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.10.4 (stable) (Tue Dec 9 00:01:55 2025 -0800) on "macos_arm64"
// Module: packages/flutter/painting.dart
// Flags: canary, emitLibraryBundle, enableAsserts(true)
dartDevEmbedder.defineLibrary("package:flutter/painting.dart", (function load__package$58flutter__painting_dart(painting) {
  'use strict';
  let core = dartDevEmbedder.importLibrary("dart:core", function(lib) {
    core = lib;
  });
  let dart = dartDevEmbedder.importLibrary("dart:_runtime", function(lib) {
    dart = lib;
  });
  let dartx = dartDevEmbedder.importLibrary("dartx", function(lib) {
    dartx = lib;
  });
  const CT = Object.create({
    _: () => (C, CT)
  });
  (function() {
  }).prototype = painting;
  painting[dartDevEmbedder.linkSymbol] = function link__painting() {
  };
  painting[dart.libraryImportUri] = "package:flutter/painting.dart";
  return painting;
}));
dartDevEmbedder.debugger.setSourceMap("packages/flutter/painting.dart", '{"version":3,"sourceRoot":"","sources":[],"names":[],"mappings":"","file":"../../../../../../../packages/flutter/painting.dart.lib.js"}');

//# sourceMappingURL=painting.dart.lib.js.map
