// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.10.4 (stable) (Tue Dec 9 00:01:55 2025 -0800) on "macos_arm64"
// Module: packages/flutter/physics.dart
// Flags: canary, emitLibraryBundle, enableAsserts(true)
dartDevEmbedder.defineLibrary("package:flutter/physics.dart", (function load__package$58flutter__physics_dart(physics) {
  'use strict';
  let core = dartDevEmbedder.importLibrary("dart:core", function(lib) {
    core = lib;
  });
  let dart = dartDevEmbedder.importLibrary("dart:_runtime", function(lib) {
    dart = lib;
  });
  let dartx = dartDevEmbedder.importLibrary("dartx", function(lib) {
    dartx = lib;
  });
  const CT = Object.create({
    _: () => (C, CT)
  });
  (function() {
  }).prototype = physics;
  physics[dartDevEmbedder.linkSymbol] = function link__physics() {
  };
  physics[dart.libraryImportUri] = "package:flutter/physics.dart";
  return physics;
}));
dartDevEmbedder.debugger.setSourceMap("packages/flutter/physics.dart", '{"version":3,"sourceRoot":"","sources":[],"names":[],"mappings":"","file":"../../../../../../../packages/flutter/physics.dart.lib.js"}');

//# sourceMappingURL=physics.dart.lib.js.map
