// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.10.4 (stable) (Tue Dec 9 00:01:55 2025 -0800) on "macos_arm64"
// Module: packages/flutter/scheduler.dart
// Flags: canary, emitLibraryBundle, enableAsserts(true)
dartDevEmbedder.defineLibrary("package:flutter/scheduler.dart", (function load__package$58flutter__scheduler_dart(scheduler) {
  'use strict';
  let core = dartDevEmbedder.importLibrary("dart:core", function(lib) {
    core = lib;
  });
  let dart = dartDevEmbedder.importLibrary("dart:_runtime", function(lib) {
    dart = lib;
  });
  let dartx = dartDevEmbedder.importLibrary("dartx", function(lib) {
    dartx = lib;
  });
  const CT = Object.create({
    _: () => (C, CT)
  });
  (function() {
  }).prototype = scheduler;
  scheduler[dartDevEmbedder.linkSymbol] = function link__scheduler() {
  };
  scheduler[dart.libraryImportUri] = "package:flutter/scheduler.dart";
  return scheduler;
}));
dartDevEmbedder.debugger.setSourceMap("packages/flutter/scheduler.dart", '{"version":3,"sourceRoot":"","sources":[],"names":[],"mappings":"","file":"../../../../../../../packages/flutter/scheduler.dart.lib.js"}');

//# sourceMappingURL=scheduler.dart.lib.js.map
