// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.10.4 (stable) (Tue Dec 9 00:01:55 2025 -0800) on "macos_arm64"
// Module: packages/flutter/src/widgets/constants.dart
// Flags: canary, emitLibraryBundle, enableAsserts(true)
dartDevEmbedder.defineLibrary("package:flutter/src/widgets/constants.dart", (function load__package$58flutter__src__widgets__constants_dart(constants) {
  'use strict';
  let core = dartDevEmbedder.importLibrary("dart:core", function(lib) {
    core = lib;
  });
  let dart = dartDevEmbedder.importLibrary("dart:_runtime", function(lib) {
    dart = lib;
  });
  let dartx = dartDevEmbedder.importLibrary("dartx", function(lib) {
    dartx = lib;
  });
  const CT = Object.create({
    _: () => (C, CT)
  });
  var kMinInteractiveDimension = dart.privateName("package:flutter/src/widgets/constants.dart", "kMinInteractiveDimension");
  dart.declareTopLevelProperties(constants, {
    [kMinInteractiveDimension]: void 0,
    /*constants.kMinInteractiveDimension*/get kMinInteractiveDimension() {
      if (this[kMinInteractiveDimension] === void 0) {
        this[kMinInteractiveDimension] = 48;
      }
      this[kMinInteractiveDimension];
      Object.defineProperty(this, "kMinInteractiveDimension", {
        get() {
          return this[kMinInteractiveDimension];
        }
      });
      return this.kMinInteractiveDimension;
    }
  });
  (function() {
  }).prototype = constants;
  constants[dartDevEmbedder.linkSymbol] = function link__constants() {
  };
  constants[dart.libraryImportUri] = "package:flutter/src/widgets/constants.dart";
  return constants;
}));
dartDevEmbedder.debugger.setSourceMap("packages/flutter/src/widgets/constants.dart", '{"version":3,"sourceRoot":"","sources":["constants.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;MAkBa,kCAAwB","file":"../../../../../../../../../packages/flutter/src/widgets/constants.dart.lib.js"}');

//# sourceMappingURL=constants.dart.lib.js.map
