// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.10.4 (stable) (Tue Dec 9 00:01:55 2025 -0800) on "macos_arm64"
// Module: packages/flutter_mate_types/flutter_mate_types.dart
// Flags: canary, emitLibraryBundle, enableAsserts(true)
dartDevEmbedder.defineLibrary("package:flutter_mate_types/flutter_mate_types.dart", (function load__package$58flutter_mate_types__flutter_mate_types_dart(flutter_mate_types) {
  'use strict';
  let core = dartDevEmbedder.importLibrary("dart:core", function(lib) {
    core = lib;
  });
  let dart = dartDevEmbedder.importLibrary("dart:_runtime", function(lib) {
    dart = lib;
  });
  let dartx = dartDevEmbedder.importLibrary("dartx", function(lib) {
    dartx = lib;
  });
  const CT = Object.create({
    _: () => (C, CT)
  });
  (function() {
  }).prototype = flutter_mate_types;
  flutter_mate_types[dartDevEmbedder.linkSymbol] = function link__flutter_mate_types() {
  };
  flutter_mate_types[dart.libraryImportUri] = "package:flutter_mate_types/flutter_mate_types.dart";
  return flutter_mate_types;
}));
dartDevEmbedder.debugger.setSourceMap("packages/flutter_mate_types/flutter_mate_types.dart", '{"version":3,"sourceRoot":"","sources":[],"names":[],"mappings":"","file":"../../../../../../../packages/flutter_mate_types/flutter_mate_types.dart.lib.js"}');

//# sourceMappingURL=flutter_mate_types.dart.lib.js.map
