// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.10.4 (stable) (Tue Dec 9 00:01:55 2025 -0800) on "macos_arm64"
// Module: packages/flutter/src/foundation/key.dart
// Flags: canary, emitLibraryBundle, enableAsserts(true)
dartDevEmbedder.defineLibrary("package:flutter/src/foundation/key.dart", (function load__package$58flutter__src__foundation__key_dart(key) {
  'use strict';
  let core = dartDevEmbedder.importLibrary("dart:core", function(lib) {
    core = lib;
  });
  let dart_rti = dartDevEmbedder.importLibrary("dart:_rti", function(lib) {
    dart_rti = lib;
  });
  let dart = dartDevEmbedder.importLibrary("dart:_runtime", function(lib) {
    dart = lib;
  });
  let diagnostics = dartDevEmbedder.importLibrary("package:flutter/src/foundation/diagnostics.dart", function(lib) {
    diagnostics = lib;
  });
  let dartx = dartDevEmbedder.importLibrary("dartx", function(lib) {
    dartx = lib;
  });
  var $toString = dartx.toString;
  var T = {
    ValueKeyOfString: () => (T.ValueKeyOfString = dart.constFn(dart_rti._Universe.eval(dart.typeUniverse, "flutter__src__foundation__key|ValueKey<core|String>", true)))(),
    String: () => (T.String = dart.constFn(dart_rti._Universe.eval(dart.typeUniverse, "core|String", true)))(),
    StringToKey: () => (T.StringToKey = dart.constFn(dart_rti._Universe.eval(dart.typeUniverse, "flutter__src__foundation__key|Key(core|String)", true)))(),
    VoidToUniqueKey: () => (T.VoidToUniqueKey = dart.constFn(dart_rti._Universe.eval(dart.typeUniverse, "flutter__src__foundation__key|UniqueKey()", true)))(),
    TToValueKeyOfT: () => (T.TToValueKeyOfT = dart.constFn(dart_rti._Universe.eval(dart.typeUniverse, "flutter__src__foundation__key|ValueKey<0^>(0^)<core|Object?>", true)))(),
    dynamic: () => (T.dynamic = dart.constFn(dart_rti._Universe.eval(dart.typeUniverse, "@", true)))(),
    VoidTo_TypeLiteralOfT: () => (T.VoidTo_TypeLiteralOfT = dart.constFn(dart_rti._Universe.eval(dart.typeUniverse, "flutter__src__foundation__key|_TypeLiteral<0^>()<core|Object?>", true)))(),
    Type: () => (T.Type = dart.constFn(dart_rti._Universe.eval(dart.typeUniverse, "core|Type", true)))()
  };
  const CT = Object.create({
    _: () => (C, CT)
  });
  var I = ["package:flutter/src/foundation/key.dart"];
  dart.declareClass(key, 'Key', class Key {
    static ['_#new#tearOff'](value) {
      return new key.ValueKey.new(T.ValueKeyOfString(), value);
    }
  });
  (key.Key.empty = function() {
    ;
  }).prototype = key.Key.prototype;
  dart.lazyFn(key.Key['_#new#tearOff'], () => T.StringToKey());
  dart.addRtiResources(key.Key, ["flutter__src__foundation__key|Key"]);
  dart.setMethodsImmediateTargetSignature(key.Key, () => dart.global.Object.setPrototypeOf({new: "package:flutter/src/foundation/key.dart:Key"}, dart.getMethodsImmediateTargets(dart.global.Object.getPrototypeOf(key.Key))));
  dart.setStaticMethodSignature(key.Key, () => ['new']);
  dart.setLibraryUri(key.Key, I[0]);
  dart.declareClass(key, 'LocalKey', class LocalKey {});
  (key.LocalKey.new = function() {
    dart.global.Object.getPrototypeOf(key.LocalKey).empty.call(this);
    ;
  }).prototype = key.LocalKey.prototype;
  dart.addRtiResources(key.LocalKey, ["flutter__src__foundation__key|LocalKey"]);
  dart.setLibraryUri(key.LocalKey, I[0]);
  dart.declareClass(key, 'UniqueKey', class UniqueKey {
    static ['_#new#tearOff']() {
      return new key.UniqueKey.new();
    }
    toString() {
      return "[#" + diagnostics.shortHash(this) + "]";
    }
  });
  (key.UniqueKey.new = function() {
    dart.global.Object.getPrototypeOf(key.UniqueKey).new.call(this);
    ;
  }).prototype = key.UniqueKey.prototype;
  dart.lazyFn(key.UniqueKey['_#new#tearOff'], () => T.VoidToUniqueKey());
  dart.addRtiResources(key.UniqueKey, ["flutter__src__foundation__key|UniqueKey"]);
  dart.setMethodsImmediateTargetSignature(key.UniqueKey, () => dart.global.Object.setPrototypeOf({[$toString]: "package:flutter/src/foundation/key.dart:UniqueKey"}, dart.getMethodsImmediateTargets(dart.global.Object.getPrototypeOf(key.UniqueKey))));
  dart.setLibraryUri(key.UniqueKey, I[0]);
  var value = dart.privateName("package:flutter/src/foundation/key.dart", "ValueKey.value");
  var __initializing = dart.privateName("package:flutter/src/foundation/key.dart", "_#initializing");
  var _eval = dart.privateName("dart:_rti", "_eval");
  var _is = dart.privateName("dart:_rti", "_is");
  dart.declareClass(key, 'ValueKey', class ValueKey {
    get value() {
      if (this[value] === __initializing) dart.throwLateInitializationError("value");
      if (this[value] === void 0) {
        this[value] = __initializing;
        try {
          this[value] = null;
        } catch (e) {
          if (this[value] === __initializing) {
            this[value] = void 0;
          }
          throw e;
        }
      }
      return this[value];
    }
    set value(value) {
      super.value = value;
    }
    static ['_#new#tearOff'](T, value) {
      return new key.ValueKey.new(T[_eval]("flutter__src__foundation__key|ValueKey<0>"), value);
    }
    _equals(other) {
      if (other == null) return false;
      if (!dart.equals(dart.runtimeType(other), dart.runtimeType(this))) {
        return false;
      }
      return dart_rti.instanceType(this)[_eval]("flutter__src__foundation__key|ValueKey<ValueKey.T>")[_is](other) && dart.equals(other.value, this.value);
    }
    get hashCode() {
      return core.Object.hash(dart.runtimeType(this), this.value);
    }
    toString() {
      let valueString = dart.equals(dart_rti.createRuntimeType(dart_rti.instanceType(this)[_eval]("ValueKey.T")), dart_rti.createRuntimeType(T.String())) ? "<'" + dart.str(this.value) + "'>" : "<" + dart.str(this.value) + ">";
      if (dart.equals(dart.runtimeType(this), new key._TypeLiteral.new(dart_rti.instanceType(this)[_eval]("flutter__src__foundation__key|_TypeLiteral<flutter__src__foundation__key|ValueKey<ValueKey.T>>")).type)) {
        return "[" + valueString + "]";
      }
      return "[" + dart.str(dart_rti.createRuntimeType(dart_rti.instanceType(this)[_eval]("ValueKey.T"))) + " " + valueString + "]";
    }
  });
  (key.ValueKey.new = function(_ti, value$) {
    this.$ti = this.$ti || _ti || dart.getReifiedType(this);
    this[value] = value$;
    dart.global.Object.getPrototypeOf(key.ValueKey).new.call(this);
    ;
  }).prototype = key.ValueKey.prototype;
  dart.lazyGFn(key.ValueKey['_#new#tearOff'], () => T.TToValueKeyOfT(), () => dart.constList(T.dynamic(), [T.dynamic()]));
  dart.addRtiResources(key.ValueKey, ["flutter__src__foundation__key|ValueKey"]);
  dart.setMethodsImmediateTargetSignature(key.ValueKey, () => dart.global.Object.setPrototypeOf({
    _equals: "package:flutter/src/foundation/key.dart:ValueKey",
    [$toString]: "package:flutter/src/foundation/key.dart:ValueKey"
  }, dart.getMethodsImmediateTargets(dart.global.Object.getPrototypeOf(key.ValueKey))));
  dart.setLibraryUri(key.ValueKey, I[0]);
  dart.setFieldSignature(key.ValueKey, () => dart.global.Object.setPrototypeOf({value: {
      type: _ti => _ti[_eval]("ValueKey.T"),
      isConst: false,
      isFinal: true
    }}, dart.getFields(dart.global.Object.getPrototypeOf(key.ValueKey))));
  dart.declareClass(key, '_TypeLiteral', class _TypeLiteral {
    get type() {
      return dart_rti.createRuntimeType(dart_rti.instanceType(this)[_eval]("_TypeLiteral.T"));
    }
    static ['_#new#tearOff'](T) {
      return new key._TypeLiteral.new(T[_eval]("flutter__src__foundation__key|_TypeLiteral<0>"));
    }
  });
  (key._TypeLiteral.new = function(_ti) {
    this.$ti = this.$ti || _ti || dart.getReifiedType(this);
    ;
  }).prototype = key._TypeLiteral.prototype;
  dart.lazyGFn(key._TypeLiteral['_#new#tearOff'], () => T.VoidTo_TypeLiteralOfT(), () => dart.constList(T.dynamic(), [T.dynamic()]));
  dart.addRtiResources(key._TypeLiteral, ["flutter__src__foundation__key|_TypeLiteral"]);
  dart.setGetterSignature(key._TypeLiteral, () => dart.global.Object.setPrototypeOf({
    type: _ti => T.Type()
  }, dart.getGetters(dart.global.Object.getPrototypeOf(key._TypeLiteral))));
  dart.setLibraryUri(key._TypeLiteral, I[0]);
  (function() {
  }).prototype = key;
  key[dartDevEmbedder.linkSymbol] = function link__key() {
    dart.classExtends(key.Key, dartDevEmbedder.importLibrary("dart:core").Object);
    dart.classExtends(key.LocalKey, dartDevEmbedder.importLibrary("package:flutter/src/foundation/key.dart").Key);
    dart.classExtends(key.UniqueKey, dartDevEmbedder.importLibrary("package:flutter/src/foundation/key.dart").LocalKey);
    dart.classExtends(key.ValueKey, dartDevEmbedder.importLibrary("package:flutter/src/foundation/key.dart").LocalKey);
    dart.classExtends(key._TypeLiteral, dartDevEmbedder.importLibrary("dart:core").Object);
    dart.defineExtensionMethods(key.UniqueKey, ['toString']);
    dart.defineExtensionMethods(key.ValueKey, ['_equals', 'toString']);
    dart.defineExtensionAccessors(key.ValueKey, ['hashCode']);
    dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"flutter__src__foundation__key|ValueKey":{"ValueKey.T":"1","flutter__src__foundation__key|LocalKey":[],"flutter__src__foundation__key|Key":[]},"flutter__src__foundation__key|LocalKey":{"flutter__src__foundation__key|Key":[]},"core|String":{"Comparable.T":"core|String","core|Comparable":["core|String"],"core|Pattern":[]},"core|Comparable":{"Comparable.T":"1"},"flutter__src__foundation__key|UniqueKey":{"flutter__src__foundation__key|LocalKey":[],"flutter__src__foundation__key|Key":[]},"flutter__src__foundation__key|_TypeLiteral":{"_TypeLiteral.T":"1"}}'));
  };
  key[dart.libraryImportUri] = "package:flutter/src/foundation/key.dart";
  return key;
}));
dartDevEmbedder.debugger.setSourceMap("packages/flutter/src/foundation/key.dart", '{"version":3,"sourceRoot":"","sources":["key.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;EAuCmB;;;;;;;;AAcQ;;EAAO;;;;;;;;AAiBX,oBAAK,sBAAU,QAAM;IAAE;;;AAH5C;;EAAW;;;;;;;;;;IAyBH;;;;;;;;;;;;;;;;;;;;;YAGgB;;AACtB,uBAAU,iBAAN,KAAK,oBAAgB;AACvB,cAAO;;AAET,YAAa,AAAe,+FAArB,KAAK,KAA+B,YAAZ,AAAM,KAAD,QAAU;IAChD;;AAGoB,YAAO,mCAAK,OAAa;IAAM;;AAIpC,wBAAgB,YAAF,wHAAc,gBAAI,cAAK,OAAM,eAAG,cAAK;AAGhE,UAAgB,6BAAZ,OAAe,AAA4B;AAC7C,cAAO,OAAG,WAAW;;AAEvB,YAAO,gBAAG,gFAAC,MAAE,WAAW;IAC1B;;oCAzBoB;;;AAAd;;EAAoB;;;;;;;;;;;;;;;AA6BT;IAAC;;;;;;;;EACpB","file":"../../../../../../../../../packages/flutter/src/foundation/key.dart.lib.js"}');

//# sourceMappingURL=key.dart.lib.js.map
