// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.10.4 (stable) (Tue Dec 9 00:01:55 2025 -0800) on "macos_arm64"
// Module: packages/flutter/src/foundation/object.dart
// Flags: canary, emitLibraryBundle, enableAsserts(true)
dartDevEmbedder.defineLibrary("package:flutter/src/foundation/object.dart", (function load__package$58flutter__src__foundation__object_dart(object) {
  'use strict';
  let core = dartDevEmbedder.importLibrary("dart:core", function(lib) {
    core = lib;
  });
  let dart = dartDevEmbedder.importLibrary("dart:_runtime", function(lib) {
    dart = lib;
  });
  let dart_rti = dartDevEmbedder.importLibrary("dart:_rti", function(lib) {
    dart_rti = lib;
  });
  let dartx = dartDevEmbedder.importLibrary("dartx", function(lib) {
    dartx = lib;
  });
  var T = {
    VoidTobool: () => (T.VoidTobool = dart.constFn(dart_rti._Universe.eval(dart.typeUniverse, "core|bool()", true)))(),
    ObjectNAndStringToString: () => (T.ObjectNAndStringToString = dart.constFn(dart_rti._Universe.eval(dart.typeUniverse, "core|String(core|Object?,core|String)", true)))()
  };
  const CT = Object.create({
    _: () => (C, CT)
  });
  var I = ["file:///Users/wenkaifan/Development/flutter/packages/flutter/lib/src/foundation/object.dart"];
  object.objectRuntimeType = function objectRuntimeType(object, optimizedValue) {
    if (!dart.fn(() => {
      optimizedValue = dart.toString(dart.runtimeType(object));
      return true;
    }, T.VoidTobool())()) dart.assertFailed(null, I[0], 13, 10, "() {\n    optimizedValue = object.runtimeType.toString();\n    return true;\n  }()");
    return optimizedValue;
  };
  dart.lazyFn(object.objectRuntimeType, () => T.ObjectNAndStringToString());
  (function() {
  }).prototype = object;
  object[dartDevEmbedder.linkSymbol] = function link__object() {
    dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"core|String":{"Comparable.T":"core|String","core|Comparable":["core|String"],"core|Pattern":[]},"core|Comparable":{"Comparable.T":"1"}}'));
  };
  object[dart.libraryImportUri] = "package:flutter/src/foundation/object.dart";
  return object;
}));
dartDevEmbedder.debugger.setSourceMap("packages/flutter/src/foundation/object.dart", '{"version":3,"sourceRoot":"","sources":["object.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;wDAWiC,QAAe;SACvC,AAGN;AAFC,uBAAoC,cAAZ,iBAAP,MAAM;AACvB,YAAO;;AAET,UAAO,eAAc;EACvB","file":"../../../../../../../../../packages/flutter/src/foundation/object.dart.lib.js"}');

//# sourceMappingURL=object.dart.lib.js.map
